@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{baseUrl}}/identity/authenticate
Content-Type: application/json

{
  "email": "victor.lima@loldesign.com.br",
  "password": "victorlima2003"
}