@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

### @name health_checker
GET {{baseUrl}}/ok

### @name authenticate
POST {{baseUrl}}/identity/authenticate
Content-Type: application/json

{
  "email": "gabriel@loldesign.com.br",
  "password": "gabriel@lol"
}